# To test with your local Python environment, run 'mchbuild build test'.
# To use a container image, set for example '-s pythonImageName=3.11'.
default:
  - build:
      - install:
          - pythonInstall:
      - docs:
          - pythonDocs:
              pullAlways: false
  - test:
      - unit:
          - pythonTest:
              pullAlways: false
          - pythonCoverage:
              pullAlways: false
      - lint:
          - pythonLint:
              pullAlways: false
          - pythonTypeChecker:
              pullAlways: false
  - verify:
      - securityScan:
          - securityReport:
              format: [ 'html', 'sbom', 'table', 'print' ]
              severity: [ 'CRITICAL', 'HIGH' ]
              target: file://poetry.lock
              qualityGate:
                threshold: 5
                criticalFactor: 5
                highFactor: 1
      - publishSbom:
          - securityPublishSbom:
      - unitWithoutCoverage:
          # Set pythonImageName to run with image of non-default Python version
          pythonTest:
            cacheDeps: false
            withCoverage: false
  - deploy:
      - docs:
          openshiftPublishDocs:
            docSrc: doc/_build/
            docType: python
      - pypi:
          pythonPublishPackage:
            setPackageVersion: true
            pythonImageName: '3.12'
            pullAlways: false


variables:
  project: 'obsweatherscale'
  ocpHostNameForEnv:
    prod: api.cp.meteoswiss.ch:6443
