# This workflow will build and publish the Python package to PyPi and the documentation to the `gh-pages` branch of the
# repository when a new tag is added.
# It uses the `peaceiris/actions-gh-pages` action to handle the publishing.
#
# Copyright (c) 2025 MeteoSwiss, created by Michele Cattaneo; michele.cattaneo@meteoswiss.ch

name: CI_publish

on:
  push:
    tags: '**'

jobs:

  tests:
    uses: ./.github/workflows/CI_test.yaml

  publish:
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Check version in pyproject.toml against tag
      run: |
        TAG=$(echo "${GITHUB_REF#refs/tags/}")
        VERSION=$(grep '^version *= *' pyproject.toml | sed -E 's/.*= *"([^"]+)".*/\1/')
        if [ "$TAG" != "$VERSION" ]; then
          echo "Tag $TAG does not match pyproject version $VERSION"
          exit 1
        else
          echo "Tag $TAG matches pyproject version $VERSION"
        fi

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install poetry and python package
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install


    - name: Publish to TestPyPi
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.TESTPYPI_API_TOKEN }}
        poetry publish --build -r testpypi
        rm -rf dist/

    - name: Publish to PyPi
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry publish --build

    - name: Build documentation
      run: poetry run sphinx-build doc doc/_build

    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3

      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/
        force_orphan: true
